services:
  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    container_name: valhalla
    hostname: valhalla
    ports:
      - "8002:8002"
    build:
      context: .
      args:
        - VALHALLA_UID=1000
        - VALHALLA_GID=1000
    volumes:
      - ./custom_files/:/custom_files
      # - ./gtfs_feeds:/gtfs_feeds  # only enable with build_transit=True
    environment:
      - tile_urls=https://download.geofabrik.de/europe/andorra-latest.osm.pbf https://download.geofabrik.de/europe/albania-latest.osm.pbf
      - server_threads=2 # determines how many threads will be used to run the valhalla server
      - serve_tiles=True # If True, starts the service. If false, stops after building the graph.
      - use_tiles_ignore_pbf=True # load existing valhalla_tiles.tar directly
      - tileset_name=valhalla_tiles # name of the resulting graph on disk
      - build_elevation=False # build elevation with "True" or "Force": will download only the elevation for areas covered by the graph tiles
      - build_admins=False # build admins db with "True" or "Force"
      - build_time_zones=False # build timezone db with "True" or "Force"
      - build_transit=False # build transit, needs existing GTFS directories mapped to /gtfs_feeds
      - build_tar=False # build an indexed tar file from the tile_dir for faster graph loading times
      - force_rebuild=False # forces a rebuild of the routing tiles with "True"
      - update_existing_config=False # if there are new config entries in the default config, add them to the existing config
      # - path_extension=graphs  # this path will be internally appended to /custom_files; no leading or trailing path separator!

  vroom:
    image: ghcr.io/vroom-project/vroom-docker:v1.14.0
    container_name: vroom
    hostname: vroom
    volumes:
      - ./conf:/conf
    environment:
      - VROOM_ROUTER=valhalla
    ports:
      - "3000:3000"
  vroom-frontend:
    image: vroom-frontend:latest
    container_name: vroom-frontend
    hostname: vroom-frontend
    ports:
      - "9966:9966"
