routing:
  api:
    type: "valhalla"
    url: "http://valhalla:8002"
    timeout: 10

cliArgs:
  geometry: true # retrieve geometry (-g)
  planmode: false # run vroom in plan mode (-c) if set to true
  threads: 4 # number of threads to use (-t)
  explore: 5 # exploration level to use (0..5) (-x)
  limit: "10mb" # max request size
  logdir: "/.." # the path for the logs relative to ./src
  logsize: "100M" # max log file size for rotation
  maxlocations: 1000 # max number of jobs/shipments locations
  maxvehicles: 200 # max number of vehicles
  override: true # allow cli options override (-c, -g, -t and -x)
  path: "/usr/local/bin/" # VROOM path (if not in $PATH)
  port: 3000 # expressjs port
  router: "valhalla" # routing backend (osrm, libosrm or ors)
  timeout: 300000 # milli-seconds
  baseurl: "/" #base url for api
routingServers:
  osrm:
    car:
      host: "0.0.0.0"
      port: "5000"
    bike:
      host: "0.0.0.0"
      port: "5001"
    foot:
      host: "0.0.0.0"
      port: "5002"
  ors:
    driving-car:
      host: "0.0.0.0/ors/v2"
      port: "8080"
    driving-hgv:
      host: "0.0.0.0/ors/v2"
      port: "8080"
    cycling-regular:
      host: "0.0.0.0/ors/v2"
      port: "8080"
    cycling-mountain:
      host: "0.0.0.0/ors/v2"
      port: "8080"
    cycling-road:
      host: "0.0.0.0/ors/v2"
      port: "8080"
    cycling-electric:
      host: "0.0.0.0/ors/v2"
      port: "8080"
    foot-walking:
      host: "0.0.0.0/ors/v2"
      port: "8080"
    foot-hiking:
      host: "0.0.0.0/ors/v2"
      port: "8080"
  valhalla:
    auto:
      host: "valhalla"
      port: "8002"
    bicycle:
      host: "valhalla"
      port: "8002"
    pedestrian:
      host: "valhalla"
      port: "8002"
    motorcycle:
      host: "valhalla"
      port: "8002"
    motor_scooter:
      host: "valhalla"
      port: "8002"
    taxi:
      host: "valhalla"
      port: "8002"
    hov:
      host: "valhalla"
      port: "8002"
    truck:
      host: "valhalla"
      port: "8002"
    bus:
      host: "valhalla"
      port: "8002"
